apiVersion: v1
kind: Pod
metadata:
  name: mybox
  namespace: weclouddata
spec:
  restartPolicy: Always
  containers:
    - name: mybox
      image: busybox
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 250m
          memory: 256Mi
      command:
        - sleep
        - "3600"
      envFrom:
        - configMapRef:
            
            name: example-configmap
        - secretRef:
            name: example-secret

    
        

